apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: facebook
  labels:
    app: web-app
    tier: frontend-backend
    env: production
    version: v1.4
spec:
  containers:
  - name: web
    image: httpd
    ports:
    - containerPort: 80
  - name: db
    image: postgres
    ports:
    - containerPort: 5432
