---
apiVersion: v1
kind: Pod
metadata:
  name: single-pod-example
  namespace: facebook
  labels:
    app: my-web-app
    tier: frontend
    env: production
    version: v1.2
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
