apiVersion: v1
kind: Pod
metadata:
  name: db-pod-example
  namespace: twitter
  labels:
    app: my-web-app
    tier: backend
    env: production
    version: master
spec:
  containers:
  - name: postgres-container
    image: postgres
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgres/data
  volumes:
  - name: postgres-data
    hostPath:
      path: /var/lib/postgres
      type: DirectoryOrCreate
