apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  namespace: facebook
  labels:
    app: web-app
    env: production
    tier: both-frontend-backend
    version: v1.5
spec:
  containers:
  - name: web-server
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: web-app-data
      mountPath: /usr/share/nginx/html
  - name: db-server
    image: postgres
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: web-app-data
    hostPath:
      path: /var/www/html
      type: DirectoryOrCreate
  - name: postgres-data
    hostPath:
      path: /var/lib/postgresql
      type: DirectoryOrCreate
